In [2]:
print(dir(__builtins__))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BaseExceptionGroup', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EncodingWarning', 'EnvironmentError', 'Exception', 'ExceptionGroup', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWarning', 'SystemError', 'SystemExit', 'TabError', 'TimeoutError', 'True', 'TypeError', 'UnboundLocalError', 'UnicodeDecodeError', 'UnicodeEncodeError', 'UnicodeError', 'UnicodeTranslateError', 'UnicodeWarning', 'UserWarning', 'ValueError', 'Warning', 'ZeroDivisionError', '__IPYTHON__', '__build_class__', '__debug__', '__doc__', '__import__', '__loader__', '__name__', '__package__', '__spec__', 'abs', 'aiter', 'all', 'anext', 'any', 'ascii', 'bin', 'bool', 'breakpoint', 'bytearray', 'bytes', 'callable', 'chr', 'classmethod', 'compile', 'complex', 'copyright', 'credits', 'delattr', 'dict', 'dir', 'display', 'divmod', 'enumerate', 'eval', 'exec', 'execfile', 'filter', 'float', 'format', 'frozenset', 'get_ipython', 'getattr', 'globals', 'hasattr', 'hash', 'help', 'hex', 'id', 'input', 'int', 'isinstance', 'issubclass', 'iter', 'len', 'license', 'list', 'locals', 'map', 'max', 'memoryview', 'min', 'next', 'object', 'oct', 'open', 'ord', 'pow', 'print', 'property', 'range', 'repr', 'reversed', 'round', 'runfile', 'set', 'setattr', 'slice', 'sorted', 'staticmethod', 'str', 'sum', 'super', 'tuple', 'type', 'vars', 'zip']

In [3]:
import pandas as pd

# Data Collection

In [4]:
# gCO2/kWh - grid intensity is about CO2 released per unit of energy. Mostly about manufacturing, but still relevant
grid_intensity = {"china": 525, "mexico": 412, "s_korea": 390}
# gCO2/ton-km  - CO2 released per ton of commodity per kilometer transported. Different countries use different methods
ton_km = {"ship_L": 8, "ship_M": 16, "truck_US": 70, "truck_Mex": 85, "rail": 22, "air_long": 500, "air_freighter": 950}

## UN Comtrade

This dataset on on worldwide trade has useful information about the USA's import of smartphones. Here are the specific filters I used for it.

Commodity code: 851713 - Telephone sets; smartphones for cellular or other wireless networks
Trade flows: Imports
Partners: USA, Puerto Rico and US Virgin Islands
Periods(year, month): 2025

In [5]:
# initialize data. I used "index_col=False", so that the first column will be considered a part of the data and not an index

phone_trade_filepath = "data/comtrade_2025_data.csv"
df_phone_trade = pd.read_csv(phone_trade_filepath, index_col=False)

In [6]:
df_phone_trade.head()

,typeCode,freqCode,refPeriodId,refYear,refMonth,period,reporterCode,reporterISO,reporterDesc,flowCode,...,netWgt,isNetWgtEstimated,grossWgt,isGrossWgtEstimated,cifvalue,fobvalue,primaryValue,legacyEstimationFlag,isReported,isAggregate
0,C,A,20250101,2025,52,2025,31,AZE,Azerbaijan,M,...,0.250,False,0,False,225.030,NaN,225.030,0,False,True
1,C,A,20250101,2025,52,2025,32,ARG,Argentina,M,...,8.680,False,0,False,11168.330,11074.590,11168.330,0,False,True
2,C,A,20250101,2025,52,2025,36,AUS,Australia,M,...,0.000,True,0,False,723498.286,688975.953,723498.286,4,False,True
3,C,A,20250101,2025,52,2025,64,BTN,Bhutan,M,...,70.558,True,0,False,71213.374,NaN,71213.374,4,False,True
4,C,A,20250101,2025,52,2025,70,BIH,Bosnia Herzegovina,M,...,230.420,False,0,False,25489.642,NaN,25489.642,2,False,True

In [7]:
df_phone_trade.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 47 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   typeCode                  48 non-null     object
 1   freqCode                  48 non-null     object
 2   refPeriodId               48 non-null     int64
 3   refYear                   48 non-null     int64
 4   refMonth                  48 non-null     int64
 5   period                    48 non-null     int64
 6   reporterCode              48 non-null     int64
 7   reporterISO               48 non-null     object
 8   reporterDesc              48 non-null     object
 9   flowCode                  48 non-null     object
 10  flowDesc                  48 non-null     object
 11  partnerCode               48 non-null     int64
 12  partnerISO                48 non-null     object
 13  partnerDesc               48 non-null     object
 14  partner2Code              48 non-null     int64
 15  partner2ISO               48 non-null     object
 16  partner2Desc              48 non-null     object
 17  classificationCode        48 non-null     object
 18  classificationSearchCode  48 non-null     object
 19  isOriginalClassification  48 non-null     bool
 20  cmdCode                   48 non-null     int64
 21  cmdDesc                   48 non-null     object
 22  aggrLevel                 48 non-null     int64
 23  isLeaf                    48 non-null     bool
 24  customsCode               48 non-null     object
 25  customsDesc               48 non-null     object
 26  mosCode                   48 non-null     int64
 27  motCode                   48 non-null     int64
 28  motDesc                   48 non-null     object
 29  qtyUnitCode               48 non-null     int64
 30  qtyUnitAbbr               48 non-null     object
 31  qty                       48 non-null     float64
 32  isQtyEstimated            48 non-null     bool
 33  altQtyUnitCode            48 non-null     int64
 34  altQtyUnitAbbr            40 non-null     object
 35  altQty                    48 non-null     float64
 36  isAltQtyEstimated         48 non-null     bool
 37  netWgt                    48 non-null     float64
 38  isNetWgtEstimated         48 non-null     bool
 39  grossWgt                  48 non-null     int64
 40  isGrossWgtEstimated       48 non-null     bool
 41  cifvalue                  45 non-null     float64
 42  fobvalue                  16 non-null     float64
 43  primaryValue              48 non-null     float64
 44  legacyEstimationFlag      48 non-null     int64
 45  isReported                48 non-null     bool
 46  isAggregate               48 non-null     bool
dtypes: bool(8), float64(6), int64(15), object(18)
memory usage: 15.1+ KB

What do certain columns mean? To what extent could they be relevant?

## US Census

Similar to UN Comtrade, but focuses on the USA and is more laconic.

In [12]:
washing_machine_trade_filepath = "data/State Imports by HS Commodities _v3.csv"
washing_machine_df = pd.read_csv(washing_machine_trade_filepath, index_col=False, header=2)

In [13]:
washing_machine_df.head()

,State,Commodity,Country,Time,Total Value ($US),Unnamed: 5
0,All States,845011 Washing Mach Automatic W Dry Line Cap N...,China,2025,"82,435,927",NaN
1,All States,845011 Washing Mach Automatic W Dry Line Cap N...,China,2026 through March,"11,189,286",NaN
2,All States,845011 Washing Mach Automatic W Dry Line Cap N...,"Korea, South",2025,"7,091,316",NaN
3,All States,845011 Washing Mach Automatic W Dry Line Cap N...,"Korea, South",2026 through March,"1,513,645",NaN
4,All States,845011 Washing Mach Automatic W Dry Line Cap N...,Mexico,2025,"199,437,788",NaN

In [14]:
washing_machine_df["Total Value ($US)"].mean()

TypeError: Could not convert 82,435,92711,189,2867,091,3161,513,645199,437,78842,517,327242,940,01556,245,505220,865,55631,586,183223,572,79051,777,286 to numeric